### ISSUE TITLE
Direct download from link

### ISSUE THREAD

**Issue by Vivekmasona** [Dojeto/yt_downloader#5]
Sir  make direct download support from link 
Like your website link + youtube link
Then direct download
https://vivekmasona-api.herokuapp.com/download?url=https://youtu.be/z3TKq9LVbzM

**Comment by Dojeto** [comment]
This will work as an API I made a website, not an API so in my opinion, we don't need this feature :)
I still much appreciate for giving suggestions Thanks ~
